production:
  driver: org.h2.Driver
  url: "jdbc:h2:~/test"
  user: sa
  password:

  pool: 5
  timeout: 5000

development:
  driver: org.h2.Driver
  url: "jdbc:h2:/usr/local/java/projects/micro-extensions/activejdbc_m/test/test"
  user: sa
  password:
  pool: 5
  timeout: 5000

test:
  driver: org.h2.Driver
  url: "jdbc:h2:~/test"
  user: sa
  password:
  pool: 5
  timeout: 5000

#jndi: name
#  properties:{}