name: blog
description: My Blog

repositories:
  content:
    path: views/content
    cache: memCache
    default: true
    config_folder_name: config
  partials: {path: views/includes, cache: partials, default: false}
  templates: {path: views/templates}

controllers: {path: controllers, cache: controllers}

cache:
  names: [memCache, partials, views, controllers]
  class: ca.simplegames.micro.cache.DefaultCache

renderer:
  engine: velocity
  class: ca.simplegames.micro.viewers.velocity.VelocityViewRenderer
  resource_cache_enabled: true
  resource_cache_interval: 15
  global_macro_library: global_library.vm

locales:
  intercept: {parameter_name: language, scope: "session, request, context"}
  default_encoding: utf-8
  fallbak_to_system_locale: true
  resource_cache: 10
  base_names: [config/locales/messages]
  type: properties
  proprietary: true


helpers:
  - before:
      path: /^(?!\/(join|payment))/
      controller: ca.simplegames.micro.controllers.BinaryContent
      repository: [templates]
      options: {file_types: [.png, .jpg, .jpeg]}

google_analytics_code: "1111-dev-1111"

production:
  google_analytics_code: "2222-prod-2222"
