name: blog
description: My Blog

repositories:
  content:
    path: views/content
    cache: memCache
    default: true
    config: config
  partials: {path: views/partials, cache: partials, default: false, config: config}
  templates: {path: views/templates}

controllers: {path: controllers, cache: controllers}

cache:
  names: [memCache, partials, views, controllers]
  class: ca.simplegames.micro.cache.DefaultCache


template_engines:
  - engine:
      name: velocity
      class: ca.simplegames.micro.viewers.velocity.VelocityViewRenderer
      options:
          resource_cache_enabled: true
          resource_cache_interval: 15
          global_macro_library: global_library.vm
      default: true

  - engine:
      name: markdown
      class: ca.simplegames.micro.viewers.markup.MarkupViewRenderer

# MICRO_ENV: production

# optional mime types to overwrite the default
mime_types:
  .md: text/html; charset=utf8
