route:
  path: system/info
  method: get
  controller: ca.simplegames.micro.route.stats.StatsRoute

route:
  path: system/test
  method: get
  controller: demo/Demo.bsh
  repository: content
  page: system/demo.json
  options: {foo: bar}

route:
  path: hello/{name}
  method: get, post
  controller: test/Hello.bsh