# validate the YAMl structure with: http://yaml-online-parser.appspot.com/
- route: "/{image_file}.{type: png|jpg|jpeg|txt}"
  method: get, head
  controller:
    name: ca.simplegames.micro.controllers.BinaryContent
    options: {
      mime_types: { .txt: "text/plain;charset=UTF-8" }
    }

- route: /system/info
  # method: get
  controller:
    name: ca.simplegames.micro.controllers.StatsController

- route: /system/test
  method: get

  controller:
    name: demo/Demo.bsh
    options: {foo: bar}

  view:
    repository: content
    page: system/demo.json

- route: /hello/{name}
  method: get, post
  controller:
    name: test/Hello.bsh
