#alias: L10n
class: ca.simplegames.micro.extensions.i18n.I18NExtension
intercept: {parameter_name: language, scope: "session, request, context"}
default_encoding: utf-8
fallback_to_system_locale: true
resource_cache: 10
base_names: [config/locales/messages]
